
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    container_name: dev-container
    volumes:
      - ..:/home/${USER_NAME}/workspace
      - ${HOME}/.ssh:/home/${USER_NAME}/.ssh:ro
    working_dir: /home/${USER_NAME}/workspace
    stdin_open: true
    tty: true
    environment:
      - USER_NAME=${USER_NAME}
    env_file:
      - ../.env
    ports:
      - "8888:8888"